# Generated by Django 3.2 on 2025-05-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20250515_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birth_year',
            field=models.IntegerField(),
        ),
    ]
