# Generated by Django 3.2 on 2025-05-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_cat_birth_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='owner',
        ),
    ]
